# Generated by Django 2.2.5 on 2019-10-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_edge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='w',
            field=models.IntegerField(max_length=20),
        ),
    ]
