# Generated by Django 2.2.5 on 2019-10-02 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_auto_20191002_1604'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Edge',
            new_name='BookEdge',
        ),
    ]
