# Generated by Django 2.2.5 on 2019-10-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_auto_20191002_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u', models.CharField(max_length=20)),
                ('v', models.CharField(max_length=20)),
                ('w', models.IntegerField()),
            ],
        ),
    ]
