# Generated by Django 2.2.5 on 2019-10-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0006_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('pub', models.CharField(max_length=30)),
                ('pages', models.IntegerField()),
                ('price', models.IntegerField()),
                ('kind', models.CharField(max_length=30)),
                ('isbn', models.CharField(max_length=30)),
                ('imgadr', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='bookinfo_v2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('pub', models.CharField(max_length=30)),
                ('pages', models.IntegerField()),
                ('price', models.IntegerField()),
                ('kind', models.CharField(max_length=30)),
                ('imgadr', models.CharField(max_length=30)),
                ('isbn', models.CharField(max_length=30)),
            ],
        ),
    ]
